// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg3UHRc2NhgRF7hfhV9T9ZoEc4p1_smUg',
    appId: '1:104277674547:web:af5375f4a19435e254b146',
    messagingSenderId: '104277674547',
    projectId: 'microcheck-c7d98',
    authDomain: 'microcheck-c7d98.firebaseapp.com',
    storageBucket: 'microcheck-c7d98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGh1zRjSWQ__xPBVIzVOy8iiuhzOEv-Z4',
    appId: '1:104277674547:android:f27639ddb265703554b146',
    messagingSenderId: '104277674547',
    projectId: 'microcheck-c7d98',
    storageBucket: 'microcheck-c7d98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgojNunOA4C0w6iWQTXijwwa3MWwKrsNU',
    appId: '1:104277674547:ios:76f6078cde9b3d1154b146',
    messagingSenderId: '104277674547',
    projectId: 'microcheck-c7d98',
    storageBucket: 'microcheck-c7d98.appspot.com',
    iosBundleId: 'com.example.microchekApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgojNunOA4C0w6iWQTXijwwa3MWwKrsNU',
    appId: '1:104277674547:ios:76f6078cde9b3d1154b146',
    messagingSenderId: '104277674547',
    projectId: 'microcheck-c7d98',
    storageBucket: 'microcheck-c7d98.appspot.com',
    iosBundleId: 'com.example.microchekApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg3UHRc2NhgRF7hfhV9T9ZoEc4p1_smUg',
    appId: '1:104277674547:web:aeda1c322cae028554b146',
    messagingSenderId: '104277674547',
    projectId: 'microcheck-c7d98',
    authDomain: 'microcheck-c7d98.firebaseapp.com',
    storageBucket: 'microcheck-c7d98.appspot.com',
  );
}
